repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: CHANGELOG.md
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
        exclude: /template/
    -   id: debug-statements
    -   id: name-tests-test
        args: [--django]
    -   id: requirements-txt-fixer
    -   id: fix-encoding-pragma
        args: [--remove]
        exclude: ^paasta_tools/paastaapi
    -   id: pretty-format-json
        args: [
          '--autofix',
          '--indent', '4',
          '--no-sort-keys',
        ]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
        additional_dependencies: [aspy.refactor_imports==0.5.3]
        exclude: ^paasta_tools/paastaapi
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.12.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
        exclude: ^paasta_tools/paastaapi
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3.7
        args: ['--target-version', 'py37']
        exclude: ^paasta_tools/paastaapi
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        args: ['--ignore', 'E231']
        exclude: ^docs/source/conf.py|paasta_tools/paastaapi.*$
-   repo: https://github.com/Yelp/detect-secrets
    rev: 0.9.1
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*tests/.*|.*yelp/testing/.*|\.pre-commit-config\.yaml
-   repo: local
    hooks:
    -   id: patch-enforce-autospec
        name: mock.patch enforce autospec
        description: This hook ensures all mock.patch invocations specify an autospec
        entry: paasta_tools/contrib/mock_patch_checker.py
        language: script
        files: ^tests/.*\.py$|^.*_itests/.*\.py
    -   id: check-oapi-schema
        name: check that oapi.yaml is updated if paastaapi changes
        description: paastaapi is autogenerated with make openapi-codegen
        entry: paasta_tools/contrib/check_manual_oapi_changes.sh
        language: script
        exclude: ^$
        files: ^.*paasta_tools/api/api_docs/oapi.yaml|^.*paasta_tools/paastaapi.*
