-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.2
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
        exclude: /template/
    -   id: debug-statements
    -   id: name-tests-test
        args: [--django]
    -   id: requirements-txt-fixer
    -   id: flake8
        exclude: ^docs/source/conf.py$
    -   id: check-ast
    -   id: fix-encoding-pragma
        args: [--remove]
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        args: [
            '--remove-import', 'from __future__ import absolute_import',
            '--remove-import', 'from __future__ import division',
            '--remove-import', 'from __future__ import print_function',
            '--remove-import', 'from __future__ import unicode_literals',
        ]
-   repo: https://github.com/asottile/pyupgrade
    sha: v1.2.0
    hooks:
    -   id: pyupgrade
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    sha: v0.6.4
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: local
    hooks:
    -   id: patch-enforce-autospec
        name: mock.patch enforce autospec
        description: This hook ensures all mock.patch invocations specify an autospec
        entry: paasta_tools/contrib/mock_patch_checker.py
        language: script
        files: ^tests/.*\.py$
    -   id: no-catchall-except
        name: Prevent catchall except
        entry: except:$
        language: pcre
        files: \.py$
