dist: xenial
branches:
  only:
    - master
    - /^v[0-9.]+$/
    - /^travis-ci-.*$/
language: python
cache:
  pip: true
  directories:
    - .tox/
    - $HOME/.cache/pip-faster/
    - $HOME/.cache/pre-commit/
before_cache:
  # We don't currently use any secure environment variables, but just in case, and also to avoid caches that grow forever, remove log dirs.
  - rm -rf .tox/*/log .tox/log .tox/*/local/log
python:
  - "3.6"
env:
  - TOXENV=py36-linux,docs,mypy
  - TOXENV=general_itests
  - TOXENV=paasta_itests
  - TOXENV=example_cluster
  - MAKE_TARGET=itest_trusty
  - MAKE_TARGET=itest_xenial
  - MAKE_TARGET=itest_bionic
sudo: required
services:
  - docker
before_install:
  # This probably ought to match the version in yelp_package/dockerfiles/itest/mesos/Dockerfile.
  # Having a recent enough version is important so that docker features like --cpu-shares work properly.
  - sudo bash -c 'echo "deb http://repos.mesosphere.com/ubuntu xenial main" > /etc/apt/sources.list.d/mesosphere.list'
  - sudo bash -c 'echo "deb http://apt.dockerproject.org/repo ubuntu-xenial main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 81026D0004C44CF7EF55ADF8DF7D54CBE56151BF
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=1.13.1-0~ubuntu-xenial devscripts --force-yes
  - 'if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$DOCKER_USERNAME" != "" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi'
install: pip install coveralls tox==3.2 tox-pip-extensions==1.3.0
script: if [[ -n "$MAKE_TARGET" ]]; then make "$MAKE_TARGET"; else tox -i https://pypi.python.org/simple; fi
before_script:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.1/kind-linux-amd64 && chmod +x ./kind && sudo mv kind /usr/local/bin/
script: make k8s_itests
after_success:
  - coveralls
before_deploy:
  - find . -name '*.pyc' -delete
  - find . -name '__pycache__' -delete
  - sudo rm -rf paasta_tools.egg-info
deploy:
  - provider: pypi
    user: yelplabs
    password:
      secure: r9zzkDhFF/aMhId26nVuyk91t0uMLFd80ZWIXpOdGL36AvOKTj90l2Usb9ipxJeIBdiccQ5rFtX7r2RnFC9Q3cP83A0c5p1jacpb7OyNRVDaYqr/+iDVp83SQKF9l2PnKyIXeLpIbVi6x7s0L+gJ7Ex+6ck0X9V1MA1zFtFxOyhGRAPxjPhywLAIsWd7RdclD/Bg79YtZ9pZGg0QK0hm9S3RZL+e2kdM+9rNpfhmyI6Bcf6ZBMoJtsCWWRRg8JgI/StfrXs1VpJfjWmy+XApsOWTWWfjdLO3IpuDhQrAfrCwM8n7AHv8MCfxt8yPlRKA4OEg2TGOm7U+VSIubV64hgFdSt7fazYh+uttUxGE8cz8Jt/rRCYmrYmWPzm7MIoFOwBfrK7QEQDxSN9gWUbL3eWgPGQMVZC06hb0pdLog/8piNrC5DBwywlPy24ChVlt+0UMA8rzIepwX1//Bcc4a9lIxbLFg8P/1JtS7Tkfag9p2Y1Z943GU1JAHhPLktdxMxFlZ4qTfaaxz7fYU+Kr/47noNLWKtnNejVEgy4bYAR9NxDET/vnpeJ7MacefYL0zvXBWO6MCbVDCUbM8fQWrZUAjeFzMCk8kXgA1qkkQ0Lm/7ACbUUECiZ1qclZh2du6Cvt6xRsBJXDXjzYwm2ECKGS8GQ4pJ6h3DypdHgHrMM=
    on:
      tags: true
      condition: $TOXENV = paasta_itests
      repo: Yelp/paasta
  - provider: bintray
    file: "yelp_package/bintray.json"
    skip_cleanup: true  # bintray.json is generated by previous build steps.
    user: yelptravis
    key:
        secure: "RQewsXLalmlweQmEl6Opx418JihTDqEGLmfApwY4JCbRxb43aWswKBBak5hO4a3t4NF7egu0ds/dD6doNEt8iv4bo2dIpovYqKM6uxMvPTrv9ME7h5YVadJrkE91UvPqDSLTObRIuoo8JVmoOKEshQhtV8iz9cKVgJt2bf54aAwMpBOpVzLhslM6oTPFrc5atNO5X7sdz81pFJHdaR8TiMd1EABkhPs/01IOgTD649co2mlgYvq7hgNZcjAgNk4OVH5XOrhaFqFnlXFK457redPXmdjxMrS4sfo0/G1swp1zJaEUU85WWke2TOcniqt9tDp+p2eL1a9FvtXBNBLrh7kN61khz6LN3ibi+L0T1XA8Mz9H3IvPaMdqb4ESnvO6v8skEek5NLNSKXkoar9WWscAYvS3Qf1E6ixbx4XaJlmpthnetSJY7pDJ7EbiW8XDyYUwSkt0pFAbHtFK1IC/J5HJVQ3KMPXFGmXXT5i2+eZ3j1VUEh+mRc7jznKkYsbBJ1flPytGRQvkPMr0eMoAqvaul77u6oDr36umRyYA9dJs8UeHW7oQ1++1sEdktfvxKQBEY+WLTRKJHemFvsoLrIXEu9EfzTVioQw0QwzeswOg7GjU/uUHTEHBUrwFEhjgWSSI6Mg5gw5pVfkBE83Be/RbE7/8st+ky6VNaX/gKOk="
    on:
      tags: true
      condition: $MAKE_TARGET == itest_trusty || $MAKE_TARGET == itest_xenial
      repo: Yelp/paasta
