version: '2'
services:
  zookeeper:
    build: ../yelp_package/dockerfiles/itest/zookeeper/
    ports:
      - 2181

  mesosmaster:
    build: ../yelp_package/dockerfiles/itest/mesos/
    ports:
      - 5050
    command: 'mesos-master --zk=zk://zookeeper:2181/mesos-testcluster --registry=in_memory --quorum=1 --authenticate --authenticate_slaves --work_dir=/tmp/mesos --credentials=/etc/mesos-secrets'
    depends_on:
      - zookeeper

  mesosslave:
    build: ../yelp_package/dockerfiles/itest/mesos/
    ports:
      - 5051
    environment:
      CLUSTER: testcluster
    command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):10; mem(*):512; disk(*):100" --credential=/etc/mesos-slave-secret --containerizers=docker --docker=/usr/bin/docker --work_dir=/tmp/mesos --attributes="region:fakeregion;pool:default" --no-docker_kill_orphans --log_dir=/var/log/mesos'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  marathon:
    build: ../yelp_package/dockerfiles/itest/marathon/
    ports:
      - 8080
    environment:
      CLUSTER: testcluster
    command: 'marathon --zk zk://zookeeper:2181/marathon --master zk://zookeeper:2181/mesos-testcluster --no-logger --mesos_authentication --env_vars_prefix MARATHON_ --mesos_authentication_principal marathon --mesos_authentication_secret_file /etc/marathon_framework_secret'
    depends_on:
      - zookeeper

  paastatools:
    build: ../yelp_package/dockerfiles/trusty/
    environment:
      MARATHON_PORT: 'http://marathon:8080'
      MESOSMASTER_PORT: 'http://mesosmaster:5050'
      HACHECK_PORT: 'http://hacheck:6666'
      ZOOKEEPER_PORT: 'zk://zookeeper:2181'
      CHRONOS_PORT: 'http://chronos:8081'
    volumes:
    - ../:/work:rw
    depends_on:
      - zookeeper

  chronos:
    build: ../yelp_package/dockerfiles/itest/chronos/
    ports:
      - 8081
    depends_on:
      - zookeeper

  hacheck:
    build: ../yelp_package/dockerfiles/itest/hacheck/
    ports:
      - 6666
