version: '2.4'

volumes:
  nail-etc:

services:
  zookeeper:
    build: ../yelp_package/dockerfiles/itest/zookeeper/
    ports:
      - 2181

  mesosmaster:
    build: ../yelp_package/dockerfiles/itest/mesos/
    image: paasta_itest_mesos:latest
    ports:
      - 5050
    command: 'mesos-master --zk=zk://zookeeper:2181/mesos-testcluster --registry=in_memory --quorum=1 --authenticate --authenticate_slaves --work_dir=/tmp/mesos --credentials=/etc/mesos-secrets'
    depends_on:
      - zookeeper

  mesosslave:
    image: paasta_itest_mesos:latest
    ports:
      - 5051
    environment:
      CLUSTER: testcluster
    command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):10; mem(*):512; disk(*):100" --credential=/etc/mesos-slave-secret --containerizers=docker --docker=/usr/bin/docker --work_dir=/tmp/mesos --attributes="region:fakeregion;pool:default" --no-docker_kill_orphans --log_dir=/var/log/mesos'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  mesosslave2:
    image: paasta_itest_mesos:latest
    ports:
      - 5051
    environment:
      CLUSTER: testcluster
    command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):0; mem(*):0; disk(*):0" --credential=/etc/mesos-slave-secret --containerizers=docker --docker=/usr/bin/docker --work_dir=/tmp/mesos --attributes="region:otherregion;pool:default" --no-docker_kill_orphans --log_dir=/var/log/mesos'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  mesosslave3:
    image: paasta_itest_mesos:latest
    ports:
      - 5051
    environment:
      CLUSTER: testcluster
    command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):0; mem(*):0; disk(*):0" --credential=/etc/mesos-slave-secret --containerizers=docker --docker=/usr/bin/docker --work_dir=/tmp/mesos --attributes="region:fakeregion;pool:nondefault" --no-docker_kill_orphans --log_dir=/var/log/mesos'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  mesosslave4:
    image: paasta_itest_mesos:latest
    ports:
      - 5051
    environment:
      CLUSTER: testcluster
    command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):0; mem(*):0; disk(*):0" --credential=/etc/mesos-slave-secret --containerizers=docker --docker=/usr/bin/docker --work_dir=/tmp/mesos --attributes="region:otherregion;pool:nondefault" --no-docker_kill_orphans --log_dir=/var/log/mesos'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  mesosslave5:
    image: paasta_itest_mesos:latest
    ports:
      - 5051
    environment:
      CLUSTER: testcluster
    command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):0; mem(*):0; disk(*):0" --credential=/etc/mesos-slave-secret --containerizers=docker --docker=/usr/bin/docker --work_dir=/tmp/mesos --attributes="region:fakeregion;pool:nondefault;ssd:true" --no-docker_kill_orphans --log_dir=/var/log/mesos'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  paastatools:
    build: ../yelp_package/dockerfiles/xenial/
    environment:
      MESOSMASTER_PORT: 'http://mesosmaster:5050'
      HACHECK_PORT: 'http://hacheck:6666'
      ZOOKEEPER_PORT: 'zk://zookeeper:2181'
      API_PORT: 'http://paasta_api:5054'
      HTTPDRAIN_PORT: 'http://httpdrain:3000'
    volumes:
      - ../:/work:rw
      - nail-etc:/nail/etc
    depends_on:
      - zookeeper
      - paasta_api

  paasta_api:
    build:
      context: ../
      dockerfile: ./yelp_package/dockerfiles/itest/api/Dockerfile
    command: bash -c 'pip install -e /work && exec paasta-api -D 5054'
    ports:
      - 5054
    depends_on:
      - zookeeper
    volumes:
      - ../:/work:rw
      - nail-etc:/nail/etc

  hacheck:
    build: ../yelp_package/dockerfiles/itest/hacheck/
    ports:
      - 6666

  httpdrain:
    build: ../yelp_package/dockerfiles/itest/httpdrain/
    ports:
      - 3000
