zookeeper:
  build: ../yelp_package/dockerfiles/itest/zookeeper/
  ports:
    - 2181
mesosmaster:
  build: ../yelp_package/dockerfiles/itest/mesos/
  ports:
    - 5050
  links:
    - zookeeper
  command: 'mesos-master --zk=zk://zookeeper:2181/mesos-testcluster --registry=in_memory --quorum=1'

mesosslave:
  build: ../yelp_package/dockerfiles/itest/mesos/
  ports:
    - 5051
  links:
    - zookeeper
  environment:
    -CLUSTER: testcluster
  command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):10; mem(*):512"'

marathon:
  build: ../yelp_package/dockerfiles/itest/marathon/
  ports:
    - 8080
  links:
    - zookeeper
  environment:
    -CLUSTER: testcluster
  command: 'marathon --zk zk://zookeeper:2181/marathon --master zk://zookeeper:2181/mesos-testcluster --no-logger'

paastatools:
  build: ../yelp_package/dockerfiles/lucid/
  links:
    - marathon
    - mesosmaster
    - mesosslave
    - zookeeper
    - chronos
    - hacheck
  # environment:
    # -CLUSTER: testcluster ???
  # make --no-capture global ???
  volumes:
  - ../:/work:rw
  command: 'tox -e paasta_itests_inside_container -- --no-capture'

chronos:
  build: ../yelp_package/dockerfiles/itest/chronos/
  ports:
    - 8081
  links:
    - zookeeper

hacheck:
  build: ../yelp_package/dockerfiles/itest/hacheck/
  ports:
    - 6666
